name: Build and release Systemd sysext images
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v3

      # install the required dependencies
      - name: prereqs
        run: >
          sudo apt update -qq
          && sudo apt install -yqq
            curl
            jq
            squashfs-tools
            xz-utils
            gawk

      # build the images and generate a manifest
      - name: build
        run: sudo ./oven.sh

      # create a Github release with the generated artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SHA256SUMS
            *.raw
            *.conf
